server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: file://server/config


logging:
  level:
    org.springframework: INFO
    com.myapp: DEBUG